version: "3.8"
services:
  db:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: ism6562
    volumes:
      - pgdb-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: student@usf.edu
      PGADMIN_DEFAULT_PASSWORD: ism6562
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdb-data:
  pgadmin-data: