version: "3.3"
# NOTE: start_period and interval are set in the docker-compose.env file located in this
# folder. This is to allow time for one Cassandra node to start before the next one
# in the sequence. This help avoid the ring being bifurcated due to conflicts when 
# two nodes start at the same time.

networks:
  cassandra-net:
    driver: bridge

services:

  cassandra-1:
    image: "cassandra:latest"  # cassandra:4.1.3
    container_name: "cassandra-1"
    ports:
      - 7000:7000
      - 9042:9042
    networks:
      - cassandra-net
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=120M

  cassandra-2:
    image: "cassandra:latest"  # cassandra:4.1.3
    container_name: "cassandra-2"
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=120M
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2
    networks:
      - cassandra-net
    depends_on:
      - cassandra-1

  cassandra-3:
    image: "cassandra:latest"  # cassandra:4.1.3
    container_name: "cassandra-3"
    networks:
      - cassandra-net
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=120M
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2
    depends_on:
     - cassandra-2


volumes:
  data1:
  data2:
  data3:
  cassandra-node-1:
  cassandra-node-2:
  cassandra-node-3:
  